// Code generated by scripts/gen_unimplemented.sh from gen.ServerInterface; DO NOT EDIT.

package httpapi

import (
	"net/http"

	"github.com/ingki3/agent-collabortion/server/internal/httpapi/gen"
)

// unimplemented answers every operation with 501 not_implemented. Server
// embeds it so the P1 handlers only override what P1 implements.
type unimplemented struct{}

func (unimplemented) ArchiveAgent(w http.ResponseWriter, r *http.Request, agentId gen.AgentId) {
	notImplemented(w, r, "ArchiveAgent")
}

func (unimplemented) DeleteAgentProfile(w http.ResponseWriter, r *http.Request, agentId gen.AgentId, profileId gen.ProfileId) {
	notImplemented(w, r, "DeleteAgentProfile")
}

func (unimplemented) GetLane(w http.ResponseWriter, r *http.Request, laneId gen.LaneId) {
	notImplemented(w, r, "GetLane")
}

func (unimplemented) RetireMemory(w http.ResponseWriter, r *http.Request, memoryId gen.MemoryId) {
	notImplemented(w, r, "RetireMemory")
}

func (unimplemented) SupersedeMemory(w http.ResponseWriter, r *http.Request, memoryId gen.MemoryId, params gen.SupersedeMemoryParams) {
	notImplemented(w, r, "SupersedeMemory")
}

func (unimplemented) ListRoomTasks(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ListRoomTasksParams) {
	notImplemented(w, r, "ListRoomTasks")
}

func (unimplemented) UpdateRuntime(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId) {
	notImplemented(w, r, "UpdateRuntime")
}

func (unimplemented) ListMemory(w http.ResponseWriter, r *http.Request, workId gen.WorkId, params gen.ListMemoryParams) {
	notImplemented(w, r, "ListMemory")
}

func (unimplemented) NoteMemory(w http.ResponseWriter, r *http.Request, workId gen.WorkId, params gen.NoteMemoryParams) {
	notImplemented(w, r, "NoteMemory")
}

func (unimplemented) UpdateWorkspace(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "UpdateWorkspace")
}

func (unimplemented) GetOnboardingStatus(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "GetOnboardingStatus")
}
