// Code generated by scripts/gen_unimplemented.sh from gen.ServerInterface; DO NOT EDIT.

package httpapi

import (
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"

	"github.com/ingki3/agent-collabortion/server/internal/httpapi/gen"
)

// unimplemented answers every operation with 501 not_implemented. Server
// embeds it so the P1 handlers only override what P1 implements.
type unimplemented struct{}

func (unimplemented) ArchiveAgent(w http.ResponseWriter, r *http.Request, agentId gen.AgentId) {
	notImplemented(w, r, "ArchiveAgent")
}

func (unimplemented) GetAgent(w http.ResponseWriter, r *http.Request, agentId gen.AgentId) {
	notImplemented(w, r, "GetAgent")
}

func (unimplemented) UpdateAgent(w http.ResponseWriter, r *http.Request, agentId gen.AgentId) {
	notImplemented(w, r, "UpdateAgent")
}

func (unimplemented) DeleteAgentProfile(w http.ResponseWriter, r *http.Request, agentId gen.AgentId, profileId gen.ProfileId) {
	notImplemented(w, r, "DeleteAgentProfile")
}

func (unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "Login")
}

func (unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "Logout")
}

func (unimplemented) Signup(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "Signup")
}

func (unimplemented) GetCliContext(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "GetCliContext")
}

func (unimplemented) GetHitlRequest(w http.ResponseWriter, r *http.Request, hitlRequestId gen.HitlRequestId) {
	notImplemented(w, r, "GetHitlRequest")
}

func (unimplemented) ListInbox(w http.ResponseWriter, r *http.Request, params gen.ListInboxParams) {
	notImplemented(w, r, "ListInbox")
}

func (unimplemented) MarkAllInboxRead(w http.ResponseWriter, r *http.Request, params gen.MarkAllInboxReadParams) {
	notImplemented(w, r, "MarkAllInboxRead")
}

func (unimplemented) GetInboxSummary(w http.ResponseWriter, r *http.Request, params gen.GetInboxSummaryParams) {
	notImplemented(w, r, "GetInboxSummary")
}

func (unimplemented) MarkInboxRead(w http.ResponseWriter, r *http.Request, inboxItemId openapi_types.UUID) {
	notImplemented(w, r, "MarkInboxRead")
}

func (unimplemented) PreviewInvite(w http.ResponseWriter, r *http.Request, inviteToken gen.InviteToken) {
	notImplemented(w, r, "PreviewInvite")
}

func (unimplemented) AcceptInvite(w http.ResponseWriter, r *http.Request, inviteToken gen.InviteToken) {
	notImplemented(w, r, "AcceptInvite")
}

func (unimplemented) GetLane(w http.ResponseWriter, r *http.Request, laneId gen.LaneId) {
	notImplemented(w, r, "GetLane")
}

func (unimplemented) CancelLane(w http.ResponseWriter, r *http.Request, laneId gen.LaneId) {
	notImplemented(w, r, "CancelLane")
}

func (unimplemented) RestartLane(w http.ResponseWriter, r *http.Request, laneId gen.LaneId, params gen.RestartLaneParams) {
	notImplemented(w, r, "RestartLane")
}

func (unimplemented) ListLaneTasks(w http.ResponseWriter, r *http.Request, laneId gen.LaneId) {
	notImplemented(w, r, "ListLaneTasks")
}

func (unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "GetMe")
}

func (unimplemented) DeleteRuntime(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId) {
	notImplemented(w, r, "DeleteRuntime")
}

func (unimplemented) GetRuntime(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId) {
	notImplemented(w, r, "GetRuntime")
}

func (unimplemented) UpdateRuntime(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId) {
	notImplemented(w, r, "UpdateRuntime")
}

func (unimplemented) CheckRepo(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId) {
	notImplemented(w, r, "CheckRepo")
}

func (unimplemented) ListRuntimeWorkdirs(w http.ResponseWriter, r *http.Request, runtimeId gen.RuntimeId, params gen.ListRuntimeWorkdirsParams) {
	notImplemented(w, r, "ListRuntimeWorkdirs")
}

func (unimplemented) GetSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "GetSession")
}

func (unimplemented) UpdateSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "UpdateSession")
}

func (unimplemented) CancelSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "CancelSession")
}

func (unimplemented) GetSessionCost(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "GetSessionCost")
}

func (unimplemented) ChangeDirector(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "ChangeDirector")
}

func (unimplemented) ListHitlRequests(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.ListHitlRequestsParams) {
	notImplemented(w, r, "ListHitlRequests")
}

func (unimplemented) CreateHitlRequest(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.CreateHitlRequestParams) {
	notImplemented(w, r, "CreateHitlRequest")
}

func (unimplemented) ListLanes(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.ListLanesParams) {
	notImplemented(w, r, "ListLanes")
}

func (unimplemented) ListMessages(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.ListMessagesParams) {
	notImplemented(w, r, "ListMessages")
}

func (unimplemented) PostMessage(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.PostMessageParams) {
	notImplemented(w, r, "PostMessage")
}

func (unimplemented) AddParticipant(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "AddParticipant")
}

func (unimplemented) RemoveParticipant(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, agentId gen.AgentId) {
	notImplemented(w, r, "RemoveParticipant")
}

func (unimplemented) UpdateParticipant(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, agentId gen.AgentId) {
	notImplemented(w, r, "UpdateParticipant")
}

func (unimplemented) PauseSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "PauseSession")
}

func (unimplemented) RebindSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "RebindSession")
}

func (unimplemented) ResumeSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "ResumeSession")
}

func (unimplemented) StartSession(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "StartSession")
}

func (unimplemented) SetSessionSubscription(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId) {
	notImplemented(w, r, "SetSessionSubscription")
}

func (unimplemented) ListSessionTasks(w http.ResponseWriter, r *http.Request, sessionId gen.SessionId, params gen.ListSessionTasksParams) {
	notImplemented(w, r, "ListSessionTasks")
}

func (unimplemented) GetTask(w http.ResponseWriter, r *http.Request, taskId gen.TaskId) {
	notImplemented(w, r, "GetTask")
}

func (unimplemented) ListTaskEvents(w http.ResponseWriter, r *http.Request, taskId gen.TaskId, params gen.ListTaskEventsParams) {
	notImplemented(w, r, "ListTaskEvents")
}

func (unimplemented) DeleteWorkdir(w http.ResponseWriter, r *http.Request, workdirId openapi_types.UUID, params gen.DeleteWorkdirParams) {
	notImplemented(w, r, "DeleteWorkdir")
}

func (unimplemented) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	notImplemented(w, r, "ListWorkspaces")
}

func (unimplemented) CreateWorkspace(w http.ResponseWriter, r *http.Request, params gen.CreateWorkspaceParams) {
	notImplemented(w, r, "CreateWorkspace")
}

func (unimplemented) GetWorkspace(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "GetWorkspace")
}

func (unimplemented) UpdateWorkspace(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "UpdateWorkspace")
}

func (unimplemented) ListAgentTemplates(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "ListAgentTemplates")
}

func (unimplemented) ApplyAgentTemplate(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, templateKey gen.AgentTemplateKey, params gen.ApplyAgentTemplateParams) {
	notImplemented(w, r, "ApplyAgentTemplate")
}

func (unimplemented) ListAgents(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListAgentsParams) {
	notImplemented(w, r, "ListAgents")
}

func (unimplemented) CreateAgent(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.CreateAgentParams) {
	notImplemented(w, r, "CreateAgent")
}

func (unimplemented) GetWorkspaceCost(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.GetWorkspaceCostParams) {
	notImplemented(w, r, "GetWorkspaceCost")
}

func (unimplemented) ListInvites(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "ListInvites")
}

func (unimplemented) CreateInvite(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.CreateInviteParams) {
	notImplemented(w, r, "CreateInvite")
}

func (unimplemented) RevokeInvite(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, inviteId openapi_types.UUID) {
	notImplemented(w, r, "RevokeInvite")
}

func (unimplemented) ListMembers(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListMembersParams) {
	notImplemented(w, r, "ListMembers")
}

func (unimplemented) GetOnboardingStatus(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId) {
	notImplemented(w, r, "GetOnboardingStatus")
}

func (unimplemented) ListRuntimeCandidates(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListRuntimeCandidatesParams) {
	notImplemented(w, r, "ListRuntimeCandidates")
}

func (unimplemented) ListRuntimes(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListRuntimesParams) {
	notImplemented(w, r, "ListRuntimes")
}

func (unimplemented) CreatePairing(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.CreatePairingParams) {
	notImplemented(w, r, "CreatePairing")
}

func (unimplemented) GetPairing(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, pairingId openapi_types.UUID) {
	notImplemented(w, r, "GetPairing")
}

func (unimplemented) ListSessions(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListSessionsParams) {
	notImplemented(w, r, "ListSessions")
}

func (unimplemented) CreateSession(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.CreateSessionParams) {
	notImplemented(w, r, "CreateSession")
}

func (unimplemented) StreamEvents(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.StreamEventsParams) {
	notImplemented(w, r, "StreamEvents")
}

// v0.2.0 계약(PRD v0.19 R0) — 방·미션 op. R1 서버가 구현한다.

func (unimplemented) ListRooms(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListRoomsParams) {
	notImplemented(w, r, "ListRooms")
}

func (unimplemented) CreateRoom(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.CreateRoomParams) {
	notImplemented(w, r, "CreateRoom")
}

func (unimplemented) GetRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "GetRoom")
}

func (unimplemented) UpdateRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "UpdateRoom")
}

func (unimplemented) DeleteRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "DeleteRoom")
}

func (unimplemented) ArchiveRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "ArchiveRoom")
}

func (unimplemented) UnarchiveRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "UnarchiveRoom")
}

func (unimplemented) BlockRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "BlockRoom")
}

func (unimplemented) UnblockRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "UnblockRoom")
}

func (unimplemented) MarkRoomRead(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "MarkRoomRead")
}

func (unimplemented) SummarizeRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.SummarizeRoomParams) {
	notImplemented(w, r, "SummarizeRoom")
}

func (unimplemented) TransferRoomOwner(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "TransferRoomOwner")
}

func (unimplemented) SetRoomDeputy(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "SetRoomDeputy")
}

func (unimplemented) ListRoomParticipants(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ListRoomParticipantsParams) {
	notImplemented(w, r, "ListRoomParticipants")
}

func (unimplemented) AddRoomParticipant(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.AddRoomParticipantParams) {
	notImplemented(w, r, "AddRoomParticipant")
}

func (unimplemented) UpdateRoomParticipant(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, participantId gen.ParticipantId) {
	notImplemented(w, r, "UpdateRoomParticipant")
}

func (unimplemented) RemoveRoomParticipant(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, participantId gen.ParticipantId) {
	notImplemented(w, r, "RemoveRoomParticipant")
}

func (unimplemented) ListRoomLinks(w http.ResponseWriter, r *http.Request, roomId gen.RoomId) {
	notImplemented(w, r, "ListRoomLinks")
}

func (unimplemented) CreateRoomLink(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.CreateRoomLinkParams) {
	notImplemented(w, r, "CreateRoomLink")
}

func (unimplemented) DeleteRoomLink(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, roomLinkId gen.RoomLinkId) {
	notImplemented(w, r, "DeleteRoomLink")
}

func (unimplemented) ListRoomReads(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ListRoomReadsParams) {
	notImplemented(w, r, "ListRoomReads")
}

func (unimplemented) ListWorks(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ListWorksParams) {
	notImplemented(w, r, "ListWorks")
}

func (unimplemented) CreateWork(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.CreateWorkParams) {
	notImplemented(w, r, "CreateWork")
}

func (unimplemented) GetWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "GetWork")
}

func (unimplemented) UpdateWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "UpdateWork")
}

func (unimplemented) DeleteWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "DeleteWork")
}

func (unimplemented) PauseWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "PauseWork")
}

func (unimplemented) ResumeWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "ResumeWork")
}

func (unimplemented) CompleteWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "CompleteWork")
}

func (unimplemented) CancelWork(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "CancelWork")
}

func (unimplemented) ChangeWorkDirector(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "ChangeWorkDirector")
}

func (unimplemented) SetWorkSubscription(w http.ResponseWriter, r *http.Request, workId gen.WorkId) {
	notImplemented(w, r, "SetWorkSubscription")
}

func (unimplemented) SetLaneSubscription(w http.ResponseWriter, r *http.Request, laneId gen.LaneId) {
	notImplemented(w, r, "SetLaneSubscription")
}

func (unimplemented) ListWorkProposals(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ListWorkProposalsParams) {
	notImplemented(w, r, "ListWorkProposals")
}

func (unimplemented) CreateWorkProposal(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.CreateWorkProposalParams) {
	notImplemented(w, r, "CreateWorkProposal")
}

func (unimplemented) GetWorkProposal(w http.ResponseWriter, r *http.Request, workProposalId gen.WorkProposalId) {
	notImplemented(w, r, "GetWorkProposal")
}

func (unimplemented) ResolveWorkProposal(w http.ResponseWriter, r *http.Request, workProposalId gen.WorkProposalId, params gen.ResolveWorkProposalParams) {
	notImplemented(w, r, "ResolveWorkProposal")
}

func (unimplemented) ListActivityLog(w http.ResponseWriter, r *http.Request, workspaceId gen.WorkspaceId, params gen.ListActivityLogParams) {
	notImplemented(w, r, "ListActivityLog")
}

func (unimplemented) ListReadableRooms(w http.ResponseWriter, r *http.Request, params gen.ListReadableRoomsParams) {
	notImplemented(w, r, "ListReadableRooms")
}

func (unimplemented) ReadRoom(w http.ResponseWriter, r *http.Request, roomId gen.RoomId, params gen.ReadRoomParams) {
	notImplemented(w, r, "ReadRoom")
}
