/** openapi 스키마 별칭 — 화면 코드가 `components["schemas"][...]` 를 반복하지 않게. */
import type { components } from "./schema";

type S = components["schemas"];

export type User = S["User"];
export type Me = S["Me"];
export type Workspace = S["Workspace"];
export type WorkspaceWithRole = Me["workspaces"][number];
export type Member = S["Member"];
export type MemberRole = S["MemberRole"];
export type InvitePreview = S["InvitePreview"];
export type Runtime = S["Runtime"];
export type RuntimeCapability = S["RuntimeCapability"];
export type Pairing = S["Pairing"];
export type PairingStatus = Pairing["status"];
export type Agent = S["Agent"];
export type AgentStatus = S["AgentStatus"];
export type AgentRole = S["AgentRole"];
export type Session = S["Session"];
export type SessionListItem = S["SessionListItem"];
export type SessionCreate = S["SessionCreate"];
export type SessionStatus = S["SessionStatus"];
export type Participant = S["Participant"];
export type Message = S["Message"];
export type MessageKind = S["MessageKind"];
export type MessagePage = S["MessagePage"];
export type MessageCreate = S["MessageCreate"];
export type MessagePostResult = S["MessagePostResult"];
export type Mention = S["Mention"];
export type TaskEvent = S["TaskEvent"];
export type StreamEvent = S["StreamEvent"];
export type StreamEventType = StreamEvent["type"];
export type Problem = S["Problem"];

// ── P2 (T-W2) — S7 좌·우열 · S6 마법사 · S9·S10 · S11 ──
export type RespondTo = S["RespondTo"];
export type Isolation = S["Isolation"];
export type IsolationKind = S["IsolationKind"];
export type AutonomyLevel = S["AutonomyLevel"];
export type SessionLimits = S["SessionLimits"];
export type SessionUpdate = S["SessionUpdate"];
export type CompletionCondition = S["CompletionCondition"];
export type CompletionProgress = S["CompletionProgress"];
export type CompletionAtom = S["CompletionAtom"];
export type PauseReason = S["PauseReason"];
export type PausedDetail = S["PausedDetail"];
export type Lane = S["Lane"];
export type LaneStatus = S["LaneStatus"];
export type Task = S["Task"];
export type TaskStatus = S["TaskStatus"];
export type TaskAttempt = S["TaskAttempt"];
export type FailureKind = S["FailureKind"];
export type MessageCreate2 = S["MessageCreate"];
export type TriggerPreview = S["TriggerPreview"];
export type TriggerTarget = S["TriggerTarget"];
export type Artifact = S["Artifact"];
export type Decision = S["Decision"];
export type CostReport = S["CostReport"];
export type HitlRequest = S["HitlRequest"];
export type InboxItem = S["InboxItem"];
export type AgentProfile = S["AgentProfile"];
export type AgentProfileCreate = S["AgentProfileCreate"];
export type AgentProfileUpdate = S["AgentProfileUpdate"];
export type AgentCreate = S["AgentCreate"];
export type AgentUpdate = S["AgentUpdate"];
export type AgentTemplate = S["AgentTemplate"];
export type AgentTemplateKey = S["AgentTemplateKey"];
export type RuntimeKind = S["RuntimeKind"];
export type RuntimeRepo = S["RuntimeRepo"];
export type RuntimeCandidate = S["RuntimeCandidate"];
export type ColabCLI = S["ColabCLI"];
export type RepoCheck = S["RepoCheck"];

// ── P3 (T-W3) — S8 인박스 · HITL 카드 · S7 상단 액션 ──
export type HitlType = S["HitlType"];
export type HitlStatus = S["HitlStatus"];
export type HitlSource = S["HitlSource"];
export type HitlResponse = S["HitlResponse"];
export type InboxItemType = S["InboxItemType"];
export type InboxSeverity = S["InboxSeverity"];
export type InboxSummary = S["InboxSummary"];
export type SessionRef = S["SessionRef"];
