-- work_approval_held — 작업 중 승인 보류 (T-APPROVAL, openapi v0.3.3 CompletionProgress held_reason)
--
-- 번호는 PR 을 올리는 순간 origin/dev 의 마지막 + 1 로 이름만 바뀐다(Lead 규칙) —
-- 이 파일 안이나 코드 어디에서도 번호를 부르지 않는다.
--
-- 종료 조건이 user_approval 만 남기고 충족됐어도 그 미션에 실행·대기 중인 할 일이 있으면
-- 서버는 승인 요청(HITL)을 열지 않고 이 칸에 보류 시각을 적는다. 마지막 할 일이 끝나면
-- (finish·취소·실패) 다시 판정해 요청을 열고 칸을 비운다.
--
-- 표식이 따로 있어야 하는 이유: 「user_approval 만 빠졌고 열린 요청이 없다」는 Director 가
-- 거절한 뒤(E6-04 — 거절은 아무것도 다시 부르지 않는다)와 똑같이 생겼다. 표식 없이 다시
-- 판정하면 거절 직후 승인 요청이 또 뜬다.
ALTER TABLE work ADD COLUMN approval_held_at timestamptz;
