#!/bin/sh
# Regenerates internal/httpapi/gen/enum_values.gen.go: the ordered value list
# of the openapi enums named below. oapi-codegen emits the constants and
# Valid() but no list, and walks the values as a map (alphabetical) — the
# contract's own order is lost. Callers that need the closed set in contract
# order (roles.all = colab-cli.md §2 order) read it from here instead of
# retyping it. `go generate ./internal/httpapi/gen` runs it after
# oapi-codegen (gen.go's second directive), so the CI regenerate-and-diff
# catches a stale file; roles_test.go fails too.
set -e
cd "$(dirname "$0")/.."
SPEC=../contracts/openapi.yaml
OUT=internal/httpapi/gen/enum_values.gen.go
ENUMS="ColabCommand"
{
echo '// Code generated by scripts/gen_enum_values.sh from contracts/openapi.yaml; DO NOT EDIT.'
echo
echo 'package gen'
for e in $ENUMS; do
  # The schema's `enum: [a, b, c]` line (flow style — every enum in the spec is).
  vals=$(awk -v e="    $e:" '$0==e{p=1;next} p&&/^    [A-Za-z]/{exit} p&&/^      enum: \[/{print; exit}' "$SPEC" | sed -E 's/^ *enum: \[(.*)\]$/\1/' | tr -d ' ')
  if [ -z "$vals" ]; then
    echo "gen_enum_values: no flow enum for $e in $SPEC" >&2
    exit 1
  fi
  echo
  echo "// ${e}Values is every $e in contracts/openapi.yaml order."
  echo "var ${e}Values = []$e{"
  echo "$vals" | tr ',' '\n' | while IFS= read -r v; do
    name=$(echo "$v" | awk -F_ '{for(i=1;i<=NF;i++) printf "%s%s", toupper(substr($i,1,1)), substr($i,2)}')
    echo "	$e$name,"
  done
  echo "}"
done
} > "$OUT"
gofmt -w "$OUT"
