#!/bin/sh
# Regenerates internal/httpapi/unimplemented.go from gen.ServerInterface.
# Run after `go generate ./internal/httpapi/...` when the contract changes.
set -e
cd "$(dirname "$0")/.."
IFACE=$(awk '/^type ServerInterface interface/{p=1;next} p&&/^}/{p=0} p' internal/httpapi/gen/api.gen.go | grep -E "^[[:space:]]+[A-Z][A-Za-z]+\(" | sed -E 's/^[[:space:]]+//')
{
echo '// Code generated by scripts/gen_unimplemented.sh from gen.ServerInterface; DO NOT EDIT.'
echo
echo 'package httpapi'
echo
echo 'import ('
echo '	"net/http"'
echo
echo '	openapi_types "github.com/oapi-codegen/runtime/types"'
echo
echo '	"github.com/ingki3/agent-collabortion/server/internal/httpapi/gen"'
echo ')'
echo
echo '// unimplemented answers every operation with 501 not_implemented. Server'
echo '// embeds it so the P1 handlers only override what P1 implements.'
echo 'type unimplemented struct{}'
echo
echo "$IFACE" | while IFS= read -r sig; do
  name=$(echo "$sig" | sed -E 's/\(.*//')
  params=$(echo "$sig" | sed -E 's/^[A-Za-z]+\((.*)\)$/\1/')
  params=$(echo "$params" | perl -pe 's/(\w+) ((?!http\.|openapi_types\.)[A-Z]\w*)/$1 gen.$2/g')
  echo "func (unimplemented) $name($params) {"
  echo "	notImplemented(w, r, \"$name\")"
  echo "}"
  echo
done
} > internal/httpapi/unimplemented.go
gofmt -w internal/httpapi/unimplemented.go
