#!/bin/sh
# Regenerates internal/httpapi/unimplemented.go from gen.ServerInterface.
# Run after `go generate ./internal/httpapi/...` when the contract changes.
set -e
cd "$(dirname "$0")/.."
IFACE=$(awk '/^type ServerInterface interface/{p=1;next} p&&/^}/{p=0} p' internal/httpapi/gen/api.gen.go | grep -E "^[[:space:]]+[A-Z][A-Za-z]+\(" | sed -E 's/^[[:space:]]+//')
# Ops that *Server already implements get no stub (T-CARD-S, #400 CI web):
# the embedded stub would be shadowed anyway, but the file is what the web's
# drift tests read as "not implemented" (i-v11-observations).
IMPL=$(grep -h -E '^func \(s \*Server\) [A-Z][A-Za-z]+\(' $(ls internal/httpapi/*.go | grep -v -e '_test.go$' -e 'unimplemented.go$') | sed -E 's/^func \(s \*Server\) ([A-Za-z]+)\(.*/\1/' | sort -u)
{
echo '// Code generated by scripts/gen_unimplemented.sh from gen.ServerInterface; DO NOT EDIT.'
echo
echo 'package httpapi'
echo
echo 'import ('
echo '	"net/http"'
echo
# openapi_types only when a remaining stub's signature needs it.
if echo "$IFACE" | grep -v -x -F "$(echo "$IFACE" | grep -E "^($(echo $IMPL | tr ' ' '|'))\\(" )" | grep -q 'openapi_types\.'; then
  echo '	openapi_types "github.com/oapi-codegen/runtime/types"'
  echo
fi
echo '	"github.com/ingki3/agent-collabortion/server/internal/httpapi/gen"'
echo ')'
echo
echo '// unimplemented answers every operation with 501 not_implemented. Server'
echo '// embeds it so the P1 handlers only override what P1 implements.'
echo 'type unimplemented struct{}'
echo
echo "$IFACE" | while IFS= read -r sig; do
  name=$(echo "$sig" | sed -E 's/\(.*//')
  if echo "$IMPL" | grep -qx "$name"; then continue; fi
  params=$(echo "$sig" | sed -E 's/^[A-Za-z]+\((.*)\)$/\1/')
  params=$(echo "$params" | perl -pe 's/(\w+) ((?!http\.|openapi_types\.)[A-Z]\w*)/$1 gen.$2/g')
  echo "func (unimplemented) $name($params) {"
  echo "	notImplemented(w, r, \"$name\")"
  echo "}"
  echo
done
} > internal/httpapi/unimplemented.go
gofmt -w internal/httpapi/unimplemented.go
