#!/bin/sh
# Regenerates internal/httpapi/unimplemented.go from gen.ServerInterface.
# Run after `go generate ./internal/httpapi/...` when the contract changes.
set -e
cd "$(dirname "$0")/.."
IFACE=$(awk '/^type ServerInterface interface/{p=1;next} p&&/^}/{p=0} p' internal/httpapi/gen/api.gen.go | grep -E "^[[:space:]]+[A-Z][A-Za-z]+\(" | sed -E 's/^[[:space:]]+//')
# Ops that *Server already implements get no stub (T-CARD-S, #400 CI web):
# the embedded stub would be shadowed anyway, but the file is what the web's
# drift tests read as "not implemented" (i-v11-observations).
# 가정(#400 재리뷰 400c NN3): 구현은 internal/httpapi 의 비테스트 파일에 있는
# `func (s *Server) Op(` 꼴 메서드만 센다 — 수신자 이름이 s 가 아니거나 값 수신자
# `(Server)`, 하위 패키지, 다른 타입을 임베드해 승격된 메서드는 보지 못해 그 op 의
# 스텁이 다시 생긴다(런타임은 가려져 무해하지만 웹 드리프트 테스트가 미구현으로 읽는다).
# 이 꼴을 벗어나면 이 줄과 unimplemented_stubs_test.go 의 implRe 를 함께 고친다 —
# 그 테스트가 *Server 의 다른 수신자 꼴을 FAIL 로 잡는다.
IMPL=$(grep -h -E '^func \(s \*Server\) [A-Z][A-Za-z]+\(' $(ls internal/httpapi/*.go | grep -v -e '_test.go$' -e 'unimplemented.go$') | sed -E 's/^func \(s \*Server\) ([A-Za-z]+)\(.*/\1/' | sort -u)
{
echo '// Code generated by scripts/gen_unimplemented.sh from gen.ServerInterface; DO NOT EDIT.'
echo
echo 'package httpapi'
echo
echo 'import ('
echo '	"net/http"'
echo
# openapi_types only when a remaining stub's signature needs it.
if echo "$IFACE" | grep -v -x -F "$(echo "$IFACE" | grep -E "^($(echo $IMPL | tr ' ' '|'))\\(" )" | grep -q 'openapi_types\.'; then
  echo '	openapi_types "github.com/oapi-codegen/runtime/types"'
  echo
fi
echo '	"github.com/ingki3/agent-collabortion/server/internal/httpapi/gen"'
echo ')'
echo
echo '// unimplemented answers every operation with 501 not_implemented. Server'
echo '// embeds it so the P1 handlers only override what P1 implements.'
echo 'type unimplemented struct{}'
echo
echo "$IFACE" | while IFS= read -r sig; do
  name=$(echo "$sig" | sed -E 's/\(.*//')
  if echo "$IMPL" | grep -qx "$name"; then continue; fi
  params=$(echo "$sig" | sed -E 's/^[A-Za-z]+\((.*)\)$/\1/')
  params=$(echo "$params" | perl -pe 's/(\w+) ((?!http\.|openapi_types\.)[A-Z]\w*)/$1 gen.$2/g')
  echo "func (unimplemented) $name($params) {"
  echo "	notImplemented(w, r, \"$name\")"
  echo "}"
  echo
done
} > internal/httpapi/unimplemented.go
gofmt -w internal/httpapi/unimplemented.go
