// Package cardschema builds the MCP input schemas of the card tools from
// contracts/openapi.yaml (colab-cli v0.9.10 §3: 「카드 툴의 인자 스키마는
// openapi TaskCardInput(담당은 agent 이름)·CardResultInput·TaskCardPatch 에서
// 생성한다 — 셋이 손으로 갈리지 않게」). `go generate ./internal/mcp` writes
// ../card_schemas.gen.go; TestGeneratedMatchesContract fails when the file
// and the contract drift apart.
package cardschema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"

	"gopkg.in/yaml.v3"
)

// Generate returns the Go source of card_schemas.gen.go for spec.
func Generate(spec []byte) ([]byte, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(spec, &doc); err != nil {
		return nil, fmt.Errorf("cardschema: %w", err)
	}
	schemas, _ := dig(doc, "components", "schemas").(map[string]any)
	if schemas == nil {
		return nil, fmt.Errorf("cardschema: no components.schemas")
	}
	get := func(name string) (map[string]any, error) {
		s, ok := schemas[name].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("cardschema: no schema %s", name)
		}
		out, err := resolve(s, schemas, 0)
		if err != nil {
			return nil, err
		}
		return out.(map[string]any), nil
	}
	card, err := get("TaskCardInput")
	if err != nil {
		return nil, err
	}
	result, err := get("CardResultInput")
	if err != nil {
		return nil, err
	}
	patch, err := get("TaskCardPatch")
	if err != nil {
		return nil, err
	}
	str := func(desc string) map[string]any { return map[string]any{"type": "string", "description": desc} }

	// colab_card_delegate: the card's fields flat, `agent` (a participant
	// name — the CLI resolves it) in place of agent_id, plus the command's
	// own flags.
	delegate := tool(card)
	props := delegate["properties"].(map[string]any)
	delete(props, "agent_id")
	props["agent"] = str("the agent this card goes to — a participant name, e.g. \"Reviewer\" or \"@Reviewer\" (not yourself)")
	delegate["required"] = replace(delegate["required"], "agent_id", "agent")
	props["depends_on"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "lane ids this lane waits for"}
	props["profile"] = str("profile name (default: the participant's registered profile)")
	props["session"] = map[string]any{"type": "string"}
	props["idempotency_key"] = map[string]any{"type": "string"}

	report := tool(result)
	report["properties"].(map[string]any)["idempotency_key"] = map[string]any{"type": "string"}

	cardRef := str("the card: its label on this mission's board (e.g. \"C-3\") or its id")
	revise := map[string]any{
		"type":     "object",
		"required": []any{"card", "reason"},
		"properties": map[string]any{
			"card":            cardRef,
			"reason":          map[string]any{"type": "string", "minLength": 1, "description": "what is missing — goes to the assignee's next turn"},
			"patch":           strip(patch),
			"idempotency_key": map[string]any{"type": "string"},
		},
		"additionalProperties": false,
	}
	// colab_card_accept: acceptCard's requestBody (v0.3.11 — comment
	// required) plus the card reference and the key.
	acceptBody, ok := dig(doc, "paths", "/cards/{cardId}/accept", "post", "requestBody", "content", "application/json", "schema").(map[string]any)
	if !ok {
		return nil, fmt.Errorf("cardschema: no acceptCard requestBody schema")
	}
	accept := tool(acceptBody)
	aprops := accept["properties"].(map[string]any)
	if c, ok := aprops["comment"].(map[string]any); ok {
		c["description"] = "what you checked and why you judge it done — one or two sentences, shown on the result card's judgement line"
	}
	aprops["card"] = cardRef
	aprops["idempotency_key"] = map[string]any{"type": "string"}
	accept["required"] = append([]any{"card"}, accept["required"].([]any)...)
	get1 := map[string]any{"type": "object", "required": []any{"card"}, "properties": map[string]any{"card": cardRef}, "additionalProperties": false}
	list := map[string]any{"type": "object", "properties": map[string]any{"session": map[string]any{"type": "string"}}, "additionalProperties": false}

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/mcp/cardschema/gen from contracts/openapi.yaml; DO NOT EDIT.\n\npackage mcp\n\n")
	b.WriteString("// Input schemas of the card tools (colab-cli v0.9.10 §3) — TaskCardInput ·\n// CardResultInput · TaskCardPatch, generated so the tools cannot drift from\n// the contract.\nconst (\n")
	for _, kv := range []struct {
		name string
		v    map[string]any
	}{{"schemaCardDelegate", delegate}, {"schemaCardReport", report}, {"schemaCardAccept", accept}, {"schemaCardRevise", revise}, {"schemaCardGet", get1}, {"schemaCardList", list}} {
		js, err := json.Marshal(kv.v)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t%s = %q\n", kv.name, string(js))
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}

func dig(m map[string]any, path ...string) any {
	var cur any = m
	for _, p := range path {
		mm, ok := cur.(map[string]any)
		if !ok {
			return nil
		}
		cur = mm[p]
	}
	return cur
}

// resolve inlines every $ref (components.schemas only — all the card
// schemas use) and drops what JSON Schema tools do not need.
func resolve(v any, schemas map[string]any, depth int) (any, error) {
	if depth > 8 {
		return nil, fmt.Errorf("cardschema: $ref chain too deep")
	}
	switch t := v.(type) {
	case map[string]any:
		if ref, ok := t["$ref"].(string); ok {
			name := strings.TrimPrefix(ref, "#/components/schemas/")
			s, ok := schemas[name]
			if !ok {
				return nil, fmt.Errorf("cardschema: unknown $ref %s", ref)
			}
			return resolve(s, schemas, depth+1)
		}
		out := map[string]any{}
		for k, x := range t {
			if k == "default" || k == "format" {
				continue // not needed by a model; `format: uuid` stays a string
			}
			r, err := resolve(x, schemas, depth)
			if err != nil {
				return nil, err
			}
			out[k] = r
		}
		return out, nil
	case []any:
		out := make([]any, len(t))
		for i, x := range t {
			r, err := resolve(x, schemas, depth)
			if err != nil {
				return nil, err
			}
			out[i] = r
		}
		return out, nil
	}
	return v, nil
}

// strip drops a schema's read-only fields (CardEvidence.label) and its
// description, recursively, and closes objects to unknown fields.
func strip(v any) any {
	switch t := v.(type) {
	case map[string]any:
		out := map[string]any{}
		for k, x := range t {
			out[k] = strip(x)
		}
		if props, ok := out["properties"].(map[string]any); ok {
			for k, p := range props {
				if pm, ok := p.(map[string]any); ok {
					if d, _ := pm["description"].(string); strings.Contains(d, "읽기 전용") {
						delete(props, k)
					}
				}
			}
			out["additionalProperties"] = false
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, x := range t {
			out[i] = strip(x)
		}
		return out
	}
	return v
}

func tool(s map[string]any) map[string]any {
	out := strip(s).(map[string]any)
	delete(out, "description")
	return out
}

func replace(v any, from, to string) []any {
	list, _ := v.([]any)
	out := make([]any, 0, len(list))
	for _, x := range list {
		if x == from {
			x = to
		}
		out = append(out, x)
	}
	return out
}
