package cardschema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"

	"gopkg.in/yaml.v3"
)

// GenerateMemory returns the Go source of memory_schemas.gen.go for spec:
// the input schemas of the mission ledger tools (colab-cli v0.9.12 §3 —
// 「원장 툴도 같은 방식 — MemoryItemInput 및 supersedeMemory·retireMemory 의
// requestBody 에서」), built the card tools' way so they cannot drift from
// the contract. TestGeneratedMemoryMatchesContract is its drift test.
//
//   - colab_memory_note: MemoryItemInput + idempotency_key.
//   - colab_memory_supersede: supersedeMemory's requestBody + `memory` (the
//     target id — the card tools' `card` / the artifact tools' `artifact`
//     naming) + idempotency_key.
//   - colab_memory_retire: retireMemory's requestBody + `memory` (no key:
//     retireMemory declares no Idempotency-Key).
//   - colab_memory_get: listMemory's query parameters (kind · status) +
//     `work` (the mission — `--work`, as colab_room_messages names it).
func GenerateMemory(spec []byte) ([]byte, error) {
	var doc map[string]any
	if err := yaml.Unmarshal(spec, &doc); err != nil {
		return nil, fmt.Errorf("cardschema: %w", err)
	}
	schemas, _ := dig(doc, "components", "schemas").(map[string]any)
	if schemas == nil {
		return nil, fmt.Errorf("cardschema: no components.schemas")
	}
	resolved := func(v any, what string) (map[string]any, error) {
		m, ok := v.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("cardschema: no %s", what)
		}
		out, err := resolve(m, schemas, 0)
		if err != nil {
			return nil, err
		}
		return out.(map[string]any), nil
	}
	key := map[string]any{"type": "string"}
	memoryRef := map[string]any{"type": "string", "description": "the ledger item's id (MemoryItem.id, as colab_memory_get lists it)"}

	input, err := resolved(schemas["MemoryItemInput"], "schema MemoryItemInput")
	if err != nil {
		return nil, err
	}
	note := tool(input)
	note["properties"].(map[string]any)["idempotency_key"] = key

	body := func(path, op string) (map[string]any, error) {
		return resolved(dig(doc, "paths", path, "post", "requestBody", "content", "application/json", "schema"), op+" requestBody schema")
	}
	sup, err := body("/memory/{memoryId}/supersede", "supersedeMemory")
	if err != nil {
		return nil, err
	}
	supersede := tool(sup)
	supersede["properties"].(map[string]any)["memory"] = memoryRef
	supersede["properties"].(map[string]any)["idempotency_key"] = key
	supersede["required"] = append([]any{"memory"}, supersede["required"].([]any)...)

	ret, err := body("/memory/{memoryId}/retire", "retireMemory")
	if err != nil {
		return nil, err
	}
	retire := tool(ret)
	retire["properties"].(map[string]any)["memory"] = memoryRef
	retire["required"] = append([]any{"memory"}, retire["required"].([]any)...)

	params, ok := dig(doc, "paths", "/works/{workId}/memory", "get", "parameters").([]any)
	if !ok {
		return nil, fmt.Errorf("cardschema: no listMemory parameters")
	}
	getProps := map[string]any{}
	for _, p := range params {
		pm, _ := p.(map[string]any)
		if pm["in"] != "query" {
			continue
		}
		name, _ := pm["name"].(string)
		s, err := resolved(pm["schema"], "listMemory parameter "+name+" schema")
		if err != nil {
			return nil, err
		}
		getProps[name] = strip(s)
	}
	if getProps["kind"] == nil || getProps["status"] == nil {
		return nil, fmt.Errorf("cardschema: listMemory lacks the kind/status query parameters")
	}
	getProps["work"] = map[string]any{"type": "string", "description": "mission id (default: this turn's mission)"}
	get := map[string]any{"type": "object", "properties": getProps, "additionalProperties": false}

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/mcp/cardschema/gen from contracts/openapi.yaml; DO NOT EDIT.\n\npackage mcp\n\n")
	b.WriteString("// Input schemas of the mission ledger tools (colab-cli v0.9.12 §3) —\n// MemoryItemInput and the supersedeMemory · retireMemory requestBodies,\n// generated so the tools cannot drift from the contract.\nconst (\n")
	for _, kv := range []struct {
		name string
		v    map[string]any
	}{{"schemaMemoryNote", note}, {"schemaMemorySupersede", supersede}, {"schemaMemoryRetire", retire}, {"schemaMemoryGet", get}} {
		js, err := json.Marshal(kv.v)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\t%s = %q\n", kv.name, string(js))
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}
